// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB3iVqKgA6w-zvGLGeJ6iPuTU5CdvASyg',
    appId: '1:54118458668:web:327a3b5c8af9413c68f889',
    messagingSenderId: '54118458668',
    projectId: 'oligarch-498212',
    authDomain: 'oligarch-498212.firebaseapp.com',
    storageBucket: 'oligarch-498212.firebasestorage.app',
    measurementId: 'G-B7JLV4WEVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWC-yD52t99j02cYPUEBIuchF1myQU1DA',
    appId: '1:54118458668:android:e5081a7a2e41c06968f889',
    messagingSenderId: '54118458668',
    projectId: 'oligarch-498212',
    storageBucket: 'oligarch-498212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcH_glH6iCxkMml4lYAdaCr9_uOhq3Eb8',
    appId: '1:54118458668:ios:34fada895aa74a1a68f889',
    messagingSenderId: '54118458668',
    projectId: 'oligarch-498212',
    storageBucket: 'oligarch-498212.firebasestorage.app',
    iosBundleId: 'com.example.monopolyoligarch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcH_glH6iCxkMml4lYAdaCr9_uOhq3Eb8',
    appId: '1:54118458668:ios:34fada895aa74a1a68f889',
    messagingSenderId: '54118458668',
    projectId: 'oligarch-498212',
    storageBucket: 'oligarch-498212.firebasestorage.app',
    iosBundleId: 'com.example.monopolyoligarch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB3iVqKgA6w-zvGLGeJ6iPuTU5CdvASyg',
    appId: '1:54118458668:web:c42e01945827a0bd68f889',
    messagingSenderId: '54118458668',
    projectId: 'oligarch-498212',
    authDomain: 'oligarch-498212.firebaseapp.com',
    storageBucket: 'oligarch-498212.firebasestorage.app',
    measurementId: 'G-CFDXH11Y29',
  );
}
